### ISSUE TITLE
Wind implementation?

### ISSUE THREAD

**Issue by NCDKorrigan** [geosheehan/web-artillery-strike#2]
Hi!
The readme mentions wind adjustments/offset but the project website doesn't show any wind options

**Comment by geosheehan** [comment]
Wind offset is off by default since it's still in a beta phase.
You can turn it on by clicking the hamburger menu and switching the toggle for "Show Wind Compensation (BETA)"
![as1](https://user-images.githubusercontent.com/12356354/128519009-d9198301-9b7c-45c1-afc0-6cdb4840a030.PNG)
![as2](https://user-images.githubusercontent.com/12356354/128519030-f5759cf5-fd07-45fd-9e15-f81a3cb1afaf.PNG)

**Comment by NCDKorrigan** [comment]
You replied too fast I actually found the toggle :)
